import React from "react";
import * as Icon from "react-feather";
import { RxTimer } from "react-icons/rx";
import { AiFillSetting } from "react-icons/ai";
import { FaRegHandshake, FaDatabase } from "react-icons/fa";
import { FcMoneyTransfer } from "react-icons/fc";
import { FaUserDoctor } from "react-icons/fa6";
// RxTimer
const navigationConfig = [
  {
    id: "dashboard",
    title: "DASHBOARD",
    type: "item",
    permissions: ["admin", "editor"],
    navLink: "/",
  },
  {
    type: "groupHeader",
    groupTitle: "Plans",
  },
  {
    id: "InactivePlans",
    title: "INACTIVE PLANS",
    type: "item",
    icon: <RxTimer size={20} color="primary" />,
    permissions: ["admin", "editor"],
    navLink: "/app/scripts/fnIndex",
  },
  {
    id: "Activeplans",
    title: "ACTIVE PLANS",
    type: "item",
    icon: <AiFillSetting size={20} color="green" />,
    permissions: ["admin", "editor"],
    navLink: "/app/plans/CreatedPlanList",
  },
  {
    id: "GETNEWPLANS",
    title: "GET NEW PLANS",
    type: "item",
    icon: <FaRegHandshake size={20} color="blue" />,
    permissions: ["admin", "editor"],
    navLink: "/app/plans/PlanList",
  },
  {
    id: "PRESCRIPTIONS",
    title: "PRESCRIPTIONS",
    type: "item",
    icon: <FaUserDoctor size={20} color="red" />,
    permissions: ["admin", "editor"],
    navLink: "/app/applylist/visitorList",
  },
  {
    id: "CONTINUEAPPLICATION",
    title: "CONTINUE APPLICATION",
    type: "item",
    icon: <FaDatabase size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/payment/paymentHistoryList",
  },
  {
    id: "MANAGECLAIMS",
    title: "MANAGE CLAIMS",
    type: "item",
    icon: <FcMoneyTransfer size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/claims/ViewClaims",
  },
  // {
  //   id: "createPlan",
  //   title: "Created PlanList",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/plans/CreatedPlanList",
  // },
  // {
  //   id: "planDetails",
  //   title: "Plan Details",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/plans/PlanDetailList",
  // },
  // {
  //   id: "fnIndex",
  //   title: "BMI/HOP Plans",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/scripts/fnIndex",
  // },
  // {
  //   id: "fnoOption",
  //   title: "Plans",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/plans/PlanList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Apply",
  // },
  // {
  //   id: "fnoIndexList",
  //   title: "ApplyList",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/applylist/visitorList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Paymemt history",
  // },
  // {
  //   id: "usersList",
  //   title: "Paymemt history",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/payment/paymentHistoryList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Elite Network",
  // },
  // {
  //   id: "allTradeList",
  //   title: "Elite Netwirk List",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/plans/EliteNetworkList",
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Create Agent",
  // },

  // {
  //   id: "agentList",
  //   title: "AgentList ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/agent/AgentList",
  // },
  // // {
  // //   id: "userSpreedSheet",
  // //   title: "User Spreed Sheet ",
  // //   type: "item",
  // //   icon: <Icon.ArrowRight size={12} />,
  // //   permissions: ["admin", "editor"],
  // //   // navLink: "/app/package/nonActivePlanList",
  // //   navLink: "/",
  // // },
  // {
  //   id: "faqList",
  //   title: "FAQ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/faq/faqList",
  // },
  // {
  //   id: "aboutus",
  //   title: "About Us ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/pageSetUp/about/AllaboutUs",
  // },
  // {
  //   id: "helpUs",
  //   title: "Help Us",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/pageSetUP/helpUs/HelpUs",
  // },
  // {
  //   id: "TermConditionList",
  //   title: "Term And Condition ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/pageSetUp/termscondition/TermConditionList",
  // },
  // {
  //   id: "refferalWalletList",
  //   title: "Refferal Wallet ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/package/refferalWalletList",
  // },
  // {
  //   id: "discountList",
  //   title: "Discount Code List",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/discount/discountList",
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Explore",
  // },

  // {
  //   id: "startUp",
  //   title: "StartUp List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/explore/Trupee/startUp",
  // },
  // {
  //   id: "trupeeUniversity",
  //   title: "Trupee University List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/explore/Trupee/trupeeUniversity",
  // },
  // {
  //   id: "performanceSheet",
  //   title: "Performance Sheet List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/explore/Trupee/performanceSheet",
  // },
  // {
  //   id: "userPerformanceSheet",
  //   title: "User Performance Sheet List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/explore/Trupee/userPerformanceSheet",
  // },
  // {
  //   id: "refferEarn",
  //   title: "Reffer Earn List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/explore/Trupee/refferEarn",
  // },
  // {
  //   id: "opportunity",
  //   title: "Opportunity List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/explore/Trupee/opportunity",
  // },
  // {
  //   id: "tradingViewCharts",
  //   title: "Trading View Charts List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/explore/Trupee/tradingViewCharts",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Report",
  // },
  // {
  //   id: "report",
  //   title: "Report",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/pageSetUp/reportData/report",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Profile Page",
  // },

  // {
  //   id: "profile",
  //   title: "My Account",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/pages/profile",
  // },

  // {
  //   id: "transctionHistory",
  //   title: "Transction History ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/transctionhistory/transctionHistory",
  // },
  // {
  //   id: "feedbackList",
  //   title: "Feedback List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/feedback/FeedBackList",
  // },
  // {
  //   id: "userAppreciation",
  //   title: "User Appreciation List ",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={12} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/showAppre/userAppreciation",
  // },

  {
    id: "Logout",
    title: "Logout ",
    type: "item",
    icon: <Icon.ArrowRight size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/pages/login",
  },
];
export default navigationConfig;
